
export type PixiPerfectIconName = "add-reference" | "add-to-mask" | "alpha-lock" | "alpha-unlock" | "arrow-down" | "arrow-left" | "arrow-right" | "arrow-up" | "book" | "bucket" | "canvas-resize" | "center" | "chevron-down" | "chevron-left" | "chevron-right" | "chevrons-down" | "chevrons-left" | "chevrons-right" | "chevrons-up" | "chevron-up" | "circle" | "clock" | "color-palette" | "color-picker" | "color-sliders" | "colors-swap" | "compass" | "copy" | "corner-up-left" | "corner-up-right" | "create-mask" | "crop-to-selection" | "crop" | "database" | "deselect" | "droplet" | "duplicate-file" | "duplicate" | "edit" | "exit" | "eye-off" | "eye" | "file-minus90" | "file-plus" | "file-text" | "file" | "file90" | "file180" | "folder-plus" | "folder" | "globe" | "grid" | "gridlines" | "home" | "image-90" | "image" | "image90" | "image180" | "info" | "intersect" | "invert" | "lasso" | "layers" | "line" | "lock" | "log-out" | "magic-wand" | "minimize" | "merge" | "mouse-pointer" | "move-view" | "new-mask" | "paste" | "vector-pen" | "picker" | "plus-square" | "rectangle-selection" | "redo" | "reference-layer" | "resize" | "rotate-view" | "eraser" | "save" | "scissors" | "select-all" | "settings" | "sliders" | "square" | "subtract" | "sun" | "swap" | "tool" | "trash" | "undo" | "unlock" | "x-flip" | "x-selected-flip" | "y-flip" | "y-selected-flip" | "x-symmetry" | "y-symmetry" | "zoom-in" | "zoom-out" | "pen" | "link" | "search" | "hard-drive" | "copy-add" | "check" | "dot" | "paste-reference-layer" | "paste-as-new-layer" | "star" | "star-filled" | "star-half-filled" | "reset" | "message" | "download" | "youtube" | "misc" | "write" | "play" | "pause" | "timeline" | "swatches" | "nodes" | "onion" | "lowres-circle" | "snapping" | "lowres-square" | "lowres-line";

export const iconToUnicode: Record<PixiPerfectIconName, string> = {
    "add-reference": "\uE900",
    "add-to-mask": "\uE901",
    "alpha-lock": "\uE902",
    "alpha-unlock": "\uE903",
    "arrow-down": "\uE904",
    "arrow-left": "\uE905",
    "arrow-right": "\uE906",
    "arrow-up": "\uE907",
    "book": "\uE908",
    "bucket": "\uE909",
    "canvas-resize": "\uE90A",
    "center": "\uE90B",
    "chevron-down": "\uE90C",
    "chevron-left": "\uE90D",
    "chevron-right": "\uE90E",
    "chevrons-down": "\uE964",
    "chevrons-left": "\uE964",
    "chevrons-right": "\uE966",
    "chevrons-up": "\uE967",
    "chevron-up": "\uE90F",
    "circle": "\uE910",
    "clock": "\uE911",
    "color-palette": "\uE912",
    "color-picker": "\uE913",
    "color-sliders": "\uE914",
    "colors-swap": "\uE915",
    "compass": "\uE916",
    "copy": "\uE917",
    "corner-up-left": "\uE918",
    "corner-up-right": "\uE919",
    "create-mask": "\uE91A",
    "crop-to-selection": "\uE91B",
    "crop": "\uE91C",
    "database": "\uE91D",
    "deselect": "\uE91E",
    "droplet": "\uE91F",
    "duplicate-file": "\uE920",
    "duplicate": "\uE921",
    "edit": "\uE922",
    "exit": "\uE923",
    "eye-off": "\uE924",
    "eye": "\uE925",
    "file-minus90": "\uE926",
    "file-plus": "\uE927",
    "file-text": "\uE928",
    "file": "\uE929",
    "file90": "\uE92A",
    "file180": "\uE92B",
    "folder-plus": "\uE92C",
    "folder": "\uE92D",
    "globe": "\uE92E",
    "grid": "\uE92F",
    "gridlines": "\uE941",
    "home": "\uE930",
    "image-90": "\uE931",
    "image": "\uE932",
    "image90": "\uE933",
    "image180": "\uE934",
    "info": "\uE935",
    "intersect": "\uE936",
    "invert": "\uE937",
    "lasso": "\uE938",
    "layers": "\uE939",
    "line": "\uE93A",
    "lock": "\uE93B",
    "log-out": "\uE93C",
    "magic-wand": "\uE93D",
    "minimize": "\uE93E",
    "merge": "\uE93F",
    "mouse-pointer": "\uE940",
    "move-view": "\uE942",
    "new-mask": "\uE943",
    "paste": "\uE944",
    "vector-pen": "\uE945",
    "picker": "\uE946",
    "plus-square": "\uE947",
    "rectangle-selection": "\uE948",
    "redo": "\uE949",
    "reference-layer": "\uE94A",
    "resize": "\uE94B",
    "rotate-view": "\uE94C",
    "eraser": "\uE94D",
    "save": "\uE94E",
    "scissors": "\uE94F",
    "select-all": "\uE950",
    "settings": "\uE951",
    "sliders": "\uE952",
    "square": "\uE953",
    "subtract": "\uE954",
    "sun": "\uE955",
    "swap": "\uE956",
    "tool": "\uE957",
    "trash": "\uE958",
    "undo": "\uE959",
    "unlock": "\uE95A",
    "x-flip": "\uE95B",
    "x-selected-flip": "\uE95F",
    "y-flip": "\uE95E",
    "y-selected-flip": "\uE95C",
    "x-symmetry": "\uE95D",
    "y-symmetry": "\uE960",
    "zoom-in": "\uE961",
    "zoom-out": "\uE962",
    "pen": "\uE971",
    "link": "\uE96B",
    "search": "\uE976",
    "hard-drive": "\uE96C",
    "copy-add": "\ue921",
    "check": "\ue96a",
    "dot": "\ue963",
    "paste-reference-layer": "\ue977",
    "paste-as-new-layer": "\ue978",
    "star": "\ue97c",
    "star-filled": "\ue979",
    "star-half-filled": "\ue98b",
    "reset": "R",
    "message": "\uE96F",
    "download": "\uE969",
    "youtube": "\uE975",
    "misc": "\uE968",
    "write": "\uE970",
    "play": "\uE981",
    "pause": "\uE980",
    "timeline": "\uE983",
    "swatches": "\uE982",
    "nodes": "\ue984",
    "onion": "\ue985",
    "lowres-circle": "\ue986",
    "snapping": "\ue987",
    "lowres-square": "\ue988",
    "lowres-line": "\ue989",
};

export const IconNames: PixiPerfectIconName[] = [
    "add-reference",
    "add-to-mask",
    "alpha-lock",
    "alpha-unlock",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-up",
    "book",
    "bucket",
    "canvas-resize",
    "center",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevrons-down",
    "chevrons-left",
    "chevrons-right",
    "chevrons-up",
    "chevron-up",
    "circle",
    "clock",
    "color-palette",
    "color-picker",
    "color-sliders",
    "colors-swap",
    "compass",
    "copy",
    "corner-up-left",
    "corner-up-right",
    "create-mask",
    "crop-to-selection",
    "crop",
    "database",
    "deselect",
    "droplet",
    "duplicate-file",
    "duplicate",
    "edit",
    "exit",
    "eye-off",
    "eye",
    "file-minus90",
    "file-plus",
    "file-text",
    "file",
    "file90",
    "file180",
    "folder-plus",
    "folder",
    "globe",
    "grid",
    "gridlines",
    "home",
    "image-90",
    "image",
    "image90",
    "image180",
    "info",
    "intersect",
    "invert",
    "lasso",
    "layers",
    "line",
    "lock",
    "log-out",
    "magic-wand",
    "minimize",
    "merge",
    "mouse-pointer",
    "move-view",
    "new-mask",
    "paste",
    "vector-pen",
    "picker",
    "plus-square",
    "rectangle-selection",
    "redo",
    "reference-layer",
    "resize",
    "rotate-view",
    "eraser",
    "save",
    "scissors",
    "select-all",
    "settings",
    "sliders",
    "square",
    "subtract",
    "sun",
    "swap",
    "tool",
    "trash",
    "undo",
    "unlock",
    "x-flip",
    "x-selected-flip",
    "y-flip",
    "y-selected-flip",
    "x-symmetry",
    "y-symmetry",
    "zoom-in",
    "zoom-out",
    "pen",
    "link",
    "search",
    "hard-drive",
    "copy-add",
    "check",
    "dot",
    "paste-reference-layer",
    "paste-as-new-layer",
    "star",
    "star-filled",
    "star-half-filled",
    "reset",
    "message",
    "download",
    "youtube",
    "misc",
    "write",
    "play",
    "pause",
    "timeline",
    "swatches",
    "nodes",
    "onion",
    "lowres-circle",
    "snapping",
    "lowres-square",
    "lowres-line",
];
