name: Deploy PixiEditor.net to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main site
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Build main site
      - name: Install main site dependencies
        run: yarn install
        working-directory: .

      - name: Build main site
        run: yarn build
        working-directory: .

      - name: Add run ID to site
        run: echo ${{ github.run_id }} > ./website/build/gh_action.txt

      # Build docs site
      - name: Clone PixiEditor.net-Docs
        uses: actions/checkout@v4
        with:
          repository: PixiEditor/PixiEditor.net-Docs
          path: docs-source

      - name: Install docs dependencies
        run: yarn install
        working-directory: ./docs-source

      - name: Build docs site
        run: yarn build
        working-directory: ./docs-source

      # Merge docs into website
      - name: Copy docs into /docs of website build
        run: |
          mkdir -p ./website/build/docs
          cp -r ./docs-source/dist/* ./website/build/docs/

      # Upload and deploy final site
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  test:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Check for correct run ID
        run: |
          WEB_CONTENT=$(curl -s https://pixieditor.net/gh_action.txt)
          if [ "$WEB_CONTENT" = "${{ github.run_id }}" ]; then
            echo "gh action file matches the run ID."
          else
            echo "gh action file does not match the run ID."
            echo "gotten '$WEB_CONTENT' expected '${{ github.run_id }}'"
            exit 1
          fi

      - name: Audit using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://pixieditor.net
          uploadArtifacts: true
